[tool.poetry]
name = "x-poetry"
version = "0.1.0"
description = ""
authors = ["Cyril Jouve <jv.cyril@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
poetry = "*"
poetry-plugin-export = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
